name: qr_code_scanner_reader_and_generator
description: QR Code scanner reader and generator

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  qr_flutter: ^3.2.0
  qrscan: ^0.2.17
  font_awesome_flutter: ^8.10.0
  url_launcher: ^5.7.10
  clipboard: ^0.1.2+8
  toast: ^0.1.5
  image_gallery_saver: '^1.6.6'
  country_code_picker: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/qr.png

